# Generated by Django 3.2.7 on 2024-02-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('shop_owner', 'Shop Owner'), ('shop_staff', 'Shop Staff'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
