# Generated by Django 3.2.7 on 2024-02-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loaction'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Shop Name'),
        ),
    ]
