# Generated by Django 5.0 on 2023-12-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_sales_man_order_total_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="name",
            new_name="item_type",
        ),
        migrations.AddField(
            model_name="order",
            name="validated",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price_per_item",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Price Per Item",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="special_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Total Orderitem Price",
            ),
        ),
    ]
